/*
 * Saque e Pague Sonda
 * Modelo de API para o serviço de sonda da Saque e Pague. Parceiro pode requisitar o último estado de uma transação (cancelada, confirmada ou pendente) através das chamadas desta API. Caso não encontre a transação, o serviço retorna o estado pendente.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.com.saqueepague.sonda;

import br.com.saqueepague.ApiException;
import io.swagger.client.model.AuthResp;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthControllerApi
 */
@Ignore
public class AuthControllerApiTest {

    private final AuthControllerApi api = new AuthControllerApi();

    /**
     * Retorna o token de autenticação do serviço.
     *
     * Autentica o usuário e gera um token para a requisição de sonda.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void saqueepagueOauthTokenPostTest() throws ApiException {
        String grantType = null;
        String password = null;
        String username = null;
        AuthResp response = api.saqueepagueOauthTokenPost(grantType, password, username);

        // TODO: test validations
    }
}
