/*
 * Saque e Pague Sonda
 * Modelo de API para o serviço de sonda da Saque e Pague. Parceiro pode requisitar o último estado de uma transação (cancelada, confirmada ou pendente) através das chamadas desta API. Caso não encontre a transação, o serviço retorna o estado pendente.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.SondaReqInfTransacao;
import io.swagger.client.model.SondaReqTerminal;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * Objeto da requisição da sonda com informações da transação e do estabelecimento para a procura.
 */
@Schema(description = "Objeto da requisição da sonda com informações da transação e do estabelecimento para a procura.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-01-11T15:47:10.474Z[GMT]")public class SondaReq {

  @SerializedName("InfTransacao")
  private SondaReqInfTransacao infTransacao = null;

  @SerializedName("Terminal")
  private SondaReqTerminal terminal = null;
  public SondaReq infTransacao(SondaReqInfTransacao infTransacao) {
    this.infTransacao = infTransacao;
    return this;
  }

  

  /**
  * Get infTransacao
  * @return infTransacao
  **/
  @Schema(required = true, description = "")
  public SondaReqInfTransacao getInfTransacao() {
    return infTransacao;
  }
  public void setInfTransacao(SondaReqInfTransacao infTransacao) {
    this.infTransacao = infTransacao;
  }
  public SondaReq terminal(SondaReqTerminal terminal) {
    this.terminal = terminal;
    return this;
  }

  

  /**
  * Get terminal
  * @return terminal
  **/
  @Schema(required = true, description = "")
  public SondaReqTerminal getTerminal() {
    return terminal;
  }
  public void setTerminal(SondaReqTerminal terminal) {
    this.terminal = terminal;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SondaReq sondaReq = (SondaReq) o;
    return Objects.equals(this.infTransacao, sondaReq.infTransacao) &&
        Objects.equals(this.terminal, sondaReq.terminal);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(infTransacao, terminal);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SondaReq {\n");
    
    sb.append("    infTransacao: ").append(toIndentedString(infTransacao)).append("\n");
    sb.append("    terminal: ").append(toIndentedString(terminal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
