/*
 * Saque e Pague Sonda
 * Modelo de API para o serviço de sonda da Saque e Pague. Parceiro pode requisitar o último estado de uma transação (cancelada, confirmada ou pendente) através das chamadas desta API. Caso não encontre a transação, o serviço retorna o estado pendente.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * Objeto de resposta que contem o estado da transação sondada. Caso não encontre a transação vai retornar estado pendente.
 */
@Schema(description = "Objeto de resposta que contem o estado da transação sondada. Caso não encontre a transação vai retornar estado pendente.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-01-11T16:00:06.901Z[GMT]")public class SondaRespInfTransacao {

  @SerializedName("status")
  private String status = null;
  public SondaRespInfTransacao status(String status) {
    this.status = status;
    return this;
  }

  

  /**
  * Status da transação nos sistemas da Saque e Pague (F &#x3D; confirmada, C &#x3D; cancelada, P &#x3D; pendente). Para casos de teste usar até 10 para retorno cancelado, até 20 para estado confirmado e o resto pendente.
  * @return status
  **/
  @Schema(example = "F", required = true, description = "Status da transação nos sistemas da Saque e Pague (F = confirmada, C = cancelada, P = pendente). Para casos de teste usar até 10 para retorno cancelado, até 20 para estado confirmado e o resto pendente.")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SondaRespInfTransacao sondaRespInfTransacao = (SondaRespInfTransacao) o;
    return Objects.equals(this.status, sondaRespInfTransacao.status);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SondaRespInfTransacao {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
