/*
 * Saque e Pague Sonda
 * Modelo de API para o serviço de sonda da Saque e Pague. Parceiro pode requisitar o último estado de uma transação (cancelada, confirmada ou pendente) através das chamadas desta API. Caso não encontre a transação, o serviço retorna o estado pendente.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.SondaRespInfTransacao;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * Objeto de resposta da sonda, contém o objeto da transação sondada. Caso não encontre a transação vai retornar estado pendente.
 */
@Schema(description = "Objeto de resposta da sonda, contém o objeto da transação sondada. Caso não encontre a transação vai retornar estado pendente.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-01-11T16:00:06.901Z[GMT]")public class SondaResp {

  @SerializedName("InfTransacao")
  private SondaRespInfTransacao infTransacao = null;
  public SondaResp infTransacao(SondaRespInfTransacao infTransacao) {
    this.infTransacao = infTransacao;
    return this;
  }

  

  /**
  * Get infTransacao
  * @return infTransacao
  **/
  @Schema(required = true, description = "")
  public SondaRespInfTransacao getInfTransacao() {
    return infTransacao;
  }
  public void setInfTransacao(SondaRespInfTransacao infTransacao) {
    this.infTransacao = infTransacao;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SondaResp sondaResp = (SondaResp) o;
    return Objects.equals(this.infTransacao, sondaResp.infTransacao);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(infTransacao);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SondaResp {\n");
    
    sb.append("    infTransacao: ").append(toIndentedString(infTransacao)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
