/*
 * Saque e Pague Sonda
 * Modelo de API para o serviço de sonda da Saque e Pague. Parceiro pode requisitar o último estado de uma transação (cancelada, confirmada ou pendente) através das chamadas desta API. Caso não encontre a transação, o serviço retorna o estado pendente.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * Objeto de requisição que contem dados do estabelecimento que gerou a transação sondada.
 */
@Schema(description = "Objeto de requisição que contem dados do estabelecimento que gerou a transação sondada.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-01-11T15:47:10.474Z[GMT]")public class SondaReqTerminal {

  @SerializedName("codEstab")
  private Long codEstab = null;
  public SondaReqTerminal codEstab(Long codEstab) {
    this.codEstab = codEstab;
    return this;
  }

  

  /**
  * Código do estabelecimento da transação original. Gerado pelo sistema da SEP.
  * minimum: 1
  * @return codEstab
  **/
  @Schema(example = "1", required = true, description = "Código do estabelecimento da transação original. Gerado pelo sistema da SEP.")
  public Long getCodEstab() {
    return codEstab;
  }
  public void setCodEstab(Long codEstab) {
    this.codEstab = codEstab;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SondaReqTerminal sondaReqTerminal = (SondaReqTerminal) o;
    return Objects.equals(this.codEstab, sondaReqTerminal.codEstab);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(codEstab);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SondaReqTerminal {\n");
    
    sb.append("    codEstab: ").append(toIndentedString(codEstab)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
