/*
 * Saque e Pague Sonda
 * Modelo de API para o serviço de sonda da Saque e Pague. Parceiro pode requisitar o último estado de uma transação (cancelada, confirmada ou pendente) através das chamadas desta API. Caso não encontre a transação, o serviço retorna o estado pendente.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.SondaReq;
import io.swagger.client.model.SondaResp;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SondaApiControllerApi
 */
@Ignore
public class SondaApiControllerApiTest {

    private final SondaApiControllerApi api = new SondaApiControllerApi();

    /**
     * Retorna o estado de uma transação.
     *
     * Procura o último estado conhecido de uma transação específica dos últimos 7 dias (casos que a sonda pode tentar verificar em finais de semana ou feriado).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void saqueepagueSondaPostTest() throws ApiException {
        SondaReq body = null;
        SondaResp response = api.saqueepagueSondaPost(body);

        // TODO: test validations
    }
}
